dist: xenial
language: ruby

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
- set -e
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
- sudo apt-get install -y python3-pip
- sudo python3 -m pip install --upgrade setuptools pip
- sudo python3 -m pip install jupyter nbconvert
- "./_tests/travis-checks --quick"

after_success:
  - .travis/push.sh

